In [1]:
import numpy as np
import pandas as pd

In [2]:
# Read gas pycnometry data
methods = pd.read_excel('~/Dropbox/Espresso/Blog/Gas Pycnometry/gaspyc-results.xlsx', sheet_name='methods', index_col='id')
methods.tail()

description                                         notes
id                                                                         
5   Brass manifold (2 phases)                                           NaN
6   Brass manifold (3 phases)  Started opening all valves before each trial
7           Positive pressure                                           NaN
8   Brass manifold (2 phases)                             After re-assembly
9   Brass manifold (2 phases)                             Automatic version

In [3]:
methods.to_csv('methods.csv')

In [4]:
samples = pd.read_excel('~/Dropbox/Espresso/Blog/Gas Pycnometry/gaspyc-results.xlsx', sheet_name='samples', index_col='id')
samples.tail()

date  weight  volume  bag_id  grinder_cal_id  grind_setting  \
id                                                                      
990 2025-02-15    0.00    0.00     NaN             NaN            NaN   
991 2025-02-15  269.35   34.05     NaN             NaN            NaN   
992 2025-02-16   18.32     NaN   159.0            14.0            2.4   
993 2025-02-16    0.00    0.00     NaN             NaN            NaN   
994 2025-02-16  269.20   34.05     NaN             NaN            NaN   

     shot_id  depth_id  method_id                   description notes  
id                                                                     
990      NaN       NaN          9                         Empty   NaN  
991      NaN       NaN          9                75 balls (old)   NaN  
992   1987.0    1462.0          9  Irineo Ramirez (2.40) ground   NaN  
993      NaN       NaN          9                         Empty   NaN  
994      NaN       NaN          9                75 balls (old)   NaN

In [5]:
samples.to_csv('samples.csv')

In [6]:
trials = pd.read_excel('~/Dropbox/Espresso/Blog/Gas Pycnometry/gaspyc-results.xlsx', sheet_name='trials', index_col='id')
trials.tail()

sample_id               filename
id                                    
2975        993  trials/trial-2975.csv
2976        993  trials/trial-2976.csv
2977        994  trials/trial-2977.csv
2978        994  trials/trial-2978.csv
2979        994  trials/trial-2979.csv

In [7]:
trials.to_csv('trials.csv')

In [8]:
bags_used = samples.bag_id.dropna().unique()
bags_used

array([ 47.,  76.,  65.,  77.,  78.,  80.,  79.,  81.,  82.,  83.,  84.,
        85.,  87.,  88., 117., 119., 118., 120., 121., 128., 129., 130.,
       131., 122., 132., 133., 134., 135., 138., 139., 136., 140., 142.,
       141., 137., 143., 144., 146., 147., 148., 150., 151., 152., 154.,
       153., 155., 145., 156.,  52.,  53., 157., 158., 159.])

In [9]:
bags = pd.read_excel('~/Dropbox/Espresso/database.xlsx', sheet_name='bags', index_col='id')
bags.tail()

brand_id roast_date best_before_date freezer_date
id                                                    
155       107 2024-12-02              NaT          NaT
156       108 2024-12-26              NaT          NaT
157       109 2024-12-05              NaT          NaT
158       110 2024-12-17              NaT          NaT
159       111 2024-12-23              NaT          NaT

In [10]:
bags = bags[[i in bags_used for i in bags.index]]
bags.tail()

brand_id roast_date best_before_date freezer_date
id                                                    
155       107 2024-12-02              NaT          NaT
156       108 2024-12-26              NaT          NaT
157       109 2024-12-05              NaT          NaT
158       110 2024-12-17              NaT          NaT
159       111 2024-12-23              NaT          NaT

In [11]:
bags.to_csv('bags.csv', columns=['brand_id'])

In [12]:
brands_used = bags.brand_id.dropna().unique()
brands_used

array([ 20,  28,  29,  37,  47,  48,  49,  50,  51,  52,  53,  54,  56,
        74,  78,  79,  63,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111])

In [13]:
brands = pd.read_excel('~/Dropbox/Espresso/database.xlsx', sheet_name='brands', index_col='id')
brands.tail()

name  roaster  roast                                 notes
id                                                                       
107     Day Tripper        2    4.0            Fruit medley, honey, juicy
108     Rosso Decaf        2    9.0                Milk chocolate, raisin
109    Genji Challa       23    NaN        Grapefruit, floral, lemon-lime
110    Kianyangi AA       23    NaN  Black currant, black tea, stonefruit
111  Irineo Ramirez       23    1.0            Almond, caramel, red apple

In [14]:
brands = brands[[i in brands_used for i in brands.index]]
brands.tail()

name  roaster  roast                                 notes
id                                                                       
107     Day Tripper        2    4.0            Fruit medley, honey, juicy
108     Rosso Decaf        2    9.0                Milk chocolate, raisin
109    Genji Challa       23    NaN        Grapefruit, floral, lemon-lime
110    Kianyangi AA       23    NaN  Black currant, black tea, stonefruit
111  Irineo Ramirez       23    1.0            Almond, caramel, red apple

In [15]:
brands.to_csv('brands.csv', columns=['name'])

In [16]:
grinder_cals_used = samples.grinder_cal_id.dropna().unique()
grinder_cals_used

array([ 4., 13., 14., 15.])

In [17]:
grinder_cals = pd.read_excel('~/Dropbox/Espresso/database.xlsx', sheet_name='grinder_cals', index_col='id')
grinder_cals.tail()

date  grinder_id  zero_digits  um_per_digit  burr_angle  \
id                                                                 
12 2024-06-23           3         -1.3          30.0         0.0   
13 2024-06-23           3         -1.6          30.0         0.0   
14 2024-08-11           3         -1.6          30.0         0.0   
15 2024-11-08           4          0.3          80.0        66.0   
16 2025-01-19           4          0.1          80.0        66.0   

                                                notes  
id                                                     
12                    Used 5.0 in-lb torque on screws  
13  Used 5.0 in-lb torque on screws; cleaned pushi...  
14  Used 5.0 in-lb torque on screws; cleaned and l...  
15  Touch point has drifted; actual burr touch at ...  
16  After disassembly and cleaning; angle measured...

In [18]:
grinder_cals = grinder_cals[[i in grinder_cals_used for i in grinder_cals.index]]
grinder_cals.tail()

date  grinder_id  zero_digits  um_per_digit  burr_angle  \
id                                                                 
4         NaT           1          0.1          47.0         0.0   
13 2024-06-23           3         -1.6          30.0         0.0   
14 2024-08-11           3         -1.6          30.0         0.0   
15 2024-11-08           4          0.3          80.0        66.0   

                                                notes  
id                                                     
4   Re-aligned grinder; https://quantitativecafe.c...  
13  Used 5.0 in-lb torque on screws; cleaned pushi...  
14  Used 5.0 in-lb torque on screws; cleaned and l...  
15  Touch point has drifted; actual burr touch at ...

In [19]:
grinder_cals.to_csv('grinder_cals.csv')

In [20]:
grinders_used = grinder_cals.grinder_id.dropna().unique()
grinders_used

array([1, 3, 4])

In [21]:
grinders = pd.read_excel('~/Dropbox/Espresso/database.xlsx', sheet_name='grinders', index_col='id')
grinders.tail()

d0_pyc  d0_flow               description
id                                               
1  -653.102325      NaN  Eureka Mignon Specialita
2          NaN      NaN         Mortar and Pestle
3  -505.048847     37.0    Timemore Sculptor 078S
4  -265.388581    303.0          1Zpresso J-Ultra

In [22]:
grinders = grinders[[i in grinders_used for i in grinders.index]]
grinders.tail()

d0_pyc  d0_flow               description
id                                               
1  -653.102325      NaN  Eureka Mignon Specialita
3  -505.048847     37.0    Timemore Sculptor 078S
4  -265.388581    303.0          1Zpresso J-Ultra

In [23]:
grinders.to_csv('grinders.csv', columns=['description'])

In [24]:
depths_used = samples.depth_id.dropna().unique()
depths_used

array([ 466.,  467.,  468.,  469.,  470.,  471.,  472.,  473.,  474.,
        475.,  476.,  477.,  478.,  479.,  480.,  481.,  482.,  483.,
        484.,  485.,  486.,  487.,  488.,  490.,  489.,  492.,  493.,
        494.,  495.,  496.,  497.,  498.,  499.,  500.,  501.,  502.,
        503.,  504.,  505.,  506.,  507.,  508.,  509.,  510.,  511.,
        512.,  513.,  514.,  515.,  516.,  517.,  518.,  519.,  520.,
        525.,  526.,  527.,  528.,  529.,  530.,  531.,  533.,  534.,
        535.,  546.,  551.,  552.,  553.,  554.,  555.,  556.,  557.,
        558.,  559.,  560.,  561.,  564.,  565.,  566.,  567.,  568.,
        819.,  820.,  823.,  824.,  825.,  826.,  838.,  839.,  840.,
        841.,  844.,  845.,  846.,  847.,  848.,  849.,  854.,  855.,
        856.,  857.,  858.,  859.,  860.,  861.,  862.,  863.,  869.,
        870.,  871., 1125., 1126., 1127., 1128., 1129., 1177., 1178.,
       1179., 1180., 1181., 1182., 1183., 1184., 1185., 1186., 1187.,
       1188., 1189.,

In [25]:
depths = pd.read_excel('~/Dropbox/Espresso/database.xlsx', sheet_name='depths', index_col='id')
depths.tail()

test_date bag_id  grinder_cal_id  basket_id  puck_prep_id  tamper_id  \
id                                                                           
1458 2025-02-14    159              14          5             3          9   
1459 2025-02-14    159              14          5             3          9   
1460 2025-02-15    159              14          5             3          9   
1461 2025-02-15    159              14          5             3          9   
1462 2025-02-16    159              14          5             3          9   

      number_of_tamps  tamp_force_kg  grind_setting  weight_in_basket  \
id                                                                      
1458                1          15.64            2.0             18.01   
1459                1          15.05            2.0             18.00   
1460                1          15.41            2.0             17.99   
1461                1          15.48            2.0             18.01   
1462                1          15.68            2.4             17.98   

      depth_below_rim notes  
id                           
1458            13.28   NaN  
1459            12.97   NaN  
1460            13.45   NaN  
1461            13.26   NaN  
1462            13.15   NaN

In [26]:
depths = depths[[i in depths_used for i in depths.index]]
depths.tail()

test_date bag_id  grinder_cal_id  basket_id  puck_prep_id  tamper_id  \
id                                                                           
1458 2025-02-14    159              14          5             3          9   
1459 2025-02-14    159              14          5             3          9   
1460 2025-02-15    159              14          5             3          9   
1461 2025-02-15    159              14          5             3          9   
1462 2025-02-16    159              14          5             3          9   

      number_of_tamps  tamp_force_kg  grind_setting  weight_in_basket  \
id                                                                      
1458                1          15.64            2.0             18.01   
1459                1          15.05            2.0             18.00   
1460                1          15.41            2.0             17.99   
1461                1          15.48            2.0             18.01   
1462                1          15.68            2.4             17.98   

      depth_below_rim notes  
id                           
1458            13.28   NaN  
1459            12.97   NaN  
1460            13.45   NaN  
1461            13.26   NaN  
1462            13.15   NaN

In [27]:
depths.to_csv('depths.csv', columns=['bag_id','grinder_cal_id','basket_id','grind_setting','weight_in_basket','depth_below_rim'])

In [28]:
baskets_used = depths.basket_id.dropna().unique()
baskets_used

array([2, 5, 4])

In [29]:
baskets = pd.read_excel('~/Dropbox/Espresso/database.xlsx', sheet_name='baskets', index_col='id')
baskets.tail()

diameter  depth     volume  \
id                               
1        NaN    NaN  62.170000   
2      59.00  28.30  74.983333   
3        NaN    NaN        NaN   
4      58.65  23.35  61.450000   
5      58.74  25.26  66.903333   

                                        description  
id                                                   
1   Double basket that came with Gaggia Classic Pro  
2    Double basket that came with naked portafilter  
3                  Basket that came with Picopresso  
4                                   VST 18 g basket  
5                                   VST 20 g basket

In [30]:
baskets = baskets[[i in baskets_used for i in baskets.index]]
baskets.tail()

diameter  depth     volume                                     description
id                                                                            
2      59.00  28.30  74.983333  Double basket that came with naked portafilter
4      58.65  23.35  61.450000                                 VST 18 g basket
5      58.74  25.26  66.903333                                 VST 20 g basket

In [31]:
baskets.to_csv('baskets.csv')